export default [
  {
    id: 0,
    name: "Sitka Seafood Market",
    description:
      "E-commerce platform that offers premium wild-caught Alaska seafood straight from the fishermen and trusted partners to the customers' doorstep.",
    image: "images/projects/3.png",
    tags: [
      "React",
      "Next.js",
      "GraphQL",
      "Sanity.io",
      "TypeScript",
      "SEO",
      "E-Commerce",
    ],
    liveview: "https://sitkaseafoodmarket.com/",
    github: "/",
    alt: "Sitka Seafood Market",
  },
  {
    id: 1,
    name: "Roleplay AI Copilot",
    description:
      "Conversational AI Copilot that simulates and automates roleplay scenarios for recruitment and training purposes, for customer support teams.",
    image: "images/projects/2.png",
    tags: [
      "Python",
      "React",
      "Next.js",
      "Langchain",
      "LLM",
      "PostgreSQL",
      "FastAPI",
      "AWS",
    ],
    liveview: "https://fox.ai.fpscloud.com/",
    github: "/",
    alt: "Roleplay AI Copilot",
  },
  {
    id: 2,
    name: "Roobet",
    description:
      "Roobet Casino is Crypto's Fastest Growing Casino, and it's run by a kangaroo. Hop in, chat with friends and play 2400+ games!",
    image: "images/projects/1.png",
    tags: [
      "React",
      "Node",
      "Blockchain",
      "MongoDB",
      "Pixi.js",
      "Socket.io",
      "RethinkDB",
      "Gaming",
    ],
    liveview: "https://roobet.com/",
    github: "/",
    alt: "Roobet Crypto Casino",
  },
  {
    id: 3,
    name: "One Click DeFi",
    description:
      "Robo-advisor for DeFi: Scan your wallet address, find out your DeFi risk score, and generate the best-performing DeFi portfolios with AI.",
    image: "images/projects/4.png",
    tags: [
      "React",
      "Python",
      "Node",
      "Express",
      "TailwindCSS",
      "Blockchain",
      "DeFi",
    ],
    liveview: "https://defi.oneclick.fi/",
    github: "/",
    alt: "One Click DeFi",
  },
  {
    id: 4,
    name: "Hubrise",
    description:
      "Developer friendly Saas solution to connect to a growing ecosystem of retail and hospitality solutions with a single integration.",
    image: "images/projects/5.png",
    tags: [
      "Java",
      "React",
      "Spring Boot",
      "MaterialUI",
      "MySQL",
      "Docker",
      "TypeScript",
      "Saas",
    ],
    liveview: "https://www.hubrise.com/",
    github: "/",
    alt: "HubRise - Integration for retail and hospitality solutions",
  },
];
