export default {
  PostgreSQL: `<div class="work-item-tag" style="background: white; border: 1px solid #7C8594; color: #7C8594">PostgreSQL</div>`,
  MongoDB: `<div class="work-item-tag" style="background: white; border: 1px solid #7C8594; color: #7C8594">MongoDB</div>`,
  MySQL: `<div class="work-item-tag" style="background: white; border: 1px solid #7C8594; color: #7C8594">MySQL</div>`,
  RethinkDB: `<div class="work-item-tag" style="background: white; border: 1px solid #7C8594; color: #7C8594">RethinkDB</div>`,
  TypeScript: `<div class="work-item-tag" style="background: white; border: 1px solid #7C8594; color: #7C8594">TypeScript</div>`,
  React: `<div class="work-item-tag" style="background: #FFB800;">React</div>`,
  "Next.js": `<div class="work-item-tag" style="background: #5A69EC;">Next.js</div>`,
  Node: `<div class="work-item-tag" style="background: #5A69EC;">Node</div>`,
  LLM: `<div class="work-item-tag" style="background: #5A69EC;">LLM</div>`,
  "Pixi.js": `<div class="work-item-tag" style="background: #FFB800;">Pixi.js</div>`,
  Express: `<div class="work-item-tag" style="background: #5A69EC;">Express</div>`,
  Docker: `<div class="work-item-tag" style="background: #5A69EC;">Docker</div>`,
  FastAPI: `<div class="work-item-tag" style="background: #5A69EC;">FastAPI</div>`,
  Python: `<div class="work-item-tag" style="background: #1C49E1;">Python</div>`,
  Java: `<div class="work-item-tag" style="background: #1C49E1;">Java</div>`,
  SEO: `<div class="work-item-tag" style="background: #1C49E1;">SEO</div>`,
  "Sanity.io": `<div class="work-item-tag" style="background: #5A69EC;">Sanity.io</div>`,
  Blockchain: `<div class="work-item-tag" style="background: #21BAEB;">Blockchain</div>`,
  MaterialUI: `<div class="work-item-tag" style="background: #21BAEB;">MaterialUI</div>`,
  Langchain: `<div class="work-item-tag" style="background: #CA49F8;">Langchain</div>`,
  TailwindCSS: `<div class="work-item-tag" style="background: #CA49F8;">TailwindCSS</div>`,
  "Socket.io": `<div class="work-item-tag" style="background: #CA49F8;">Socket.io</div>`,
  Docker: `<div class="work-item-tag" style="background: #CA49F8;">Docker</div>`,
  Gaming: `<div class="work-item-tag" style="background: #1C49E1;">Gaming</div>`,
  GraphQL: `<div class="work-item-tag" style="background: #1C49E1;">GraphQL</div>`,
  DeFi: `<div class="work-item-tag" style="background: #1C49E1;">DeFi</div>`,
  "Spring Boot": `<div class="work-item-tag" style="background: #1C49E1;">Spring Boot</div>`,
  AWS: `<div class="work-item-tag" style="background: #1C49E1;">AWS</div>`,
  "E-Commerce": `<div class="work-item-tag" style="background: #1C49E1;">E-Commerce</div>`,
  Saas: `<div class="work-item-tag" style="background: #1C49E1;">Saas</div>`,
};
